import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';
import { QuizGenerationStatus } from '../../common/enums/questionsGenerationStatus.enum';
import { QuestionType } from '../../common/enums/questionsType.enum';
import { QuizDifficulty } from '../../common/enums/quizDifficulty.enum';

export type QuizDocument = HydratedDocument<Quiz>;

export interface QuizQuestion {
  _id?: Types.ObjectId;
  questionText: string;
  type: QuestionType;
  options: string[];
  correctAnswers: string[];
  isIgnored: boolean;
  createdBy: 'AI' | 'INSTRUCTOR';
}

@Schema({ _id: true, timestamps: false })
export class Question {
  @Prop({ required: true })
  questionText: string;

  @Prop({ type: String, enum: QuestionType, required: true })
  type: QuestionType;

  @Prop({ type: [String], required: true })
  options: string[];

  @Prop({ type: [String], required: true })
  correctAnswers: string[];

  // Soft-delete flag: instructor can hide an AI-generated question
  // without breaking existing attempt/answer ID references.
  @Prop({ type: Boolean, default: false })
  isIgnored: boolean;

  // Provenance flag: distinguishes AI-generated vs instructor-authored questions.
  @Prop({ type: String, enum: ['AI', 'INSTRUCTOR'], default: 'AI' })
  createdBy: 'AI' | 'INSTRUCTOR';
}

export const QuestionSchema = SchemaFactory.createForClass(Question);

@Schema({ timestamps: true })
export class Quiz {
  @Prop({ type: Types.ObjectId, ref: 'Section', required: true })
  sectionId: Types.ObjectId;
  @Prop({ type: String, enum: QuizDifficulty, required: true })
  difficulty: QuizDifficulty;
  @Prop({ required: true, min: 1, max: 50 })
  numberOfQuestions: number;
  @Prop({ type: String, enum: QuestionType, required: true })
  questionType: QuestionType;
  @Prop({
    type: String,
    enum: QuizGenerationStatus,
    default: QuizGenerationStatus.PENDING,
  })
  generationStatus: QuizGenerationStatus;
  @Prop({
    type: String,
    enum: ['pending_review', 'approved'],
    default: 'pending_review',
  })
  status: string;
  @Prop({ required: true, default: 600 })
  timeLimit: number;
  // Platform rule: passing a section quiz requires 80%, and that pass is what
  // unlocks the next section (see CoursesService.applyStudentAccess).
  @Prop({ required: true, min: 0, max: 100, default: 80 })
  passingScore: number;
  @Prop({ required: true, default: 3 })
  maxAttempts: number;
  // AI-generated by default; instructors can edit, ignore, or add questions
  // during approval (see QuizzesService.approveQuiz).
  @Prop({ type: [QuestionSchema], default: [] })
  questions: QuizQuestion[];

  @Prop({ required: true, default: 0 })
  enrollmentCountAtGeneration: number;
  
  // Track which generation number this is for the section (1st, 2nd, 3rd, etc.)
  @Prop({ required: true, default: 1 })
  quizGenerationNumber: number;
  
  // Track the enrollment count when this quiz was approved (for threshold calculation)
  @Prop({ required: true, default: 0 })
  enrollmentCountAtApproval: number;
  
  // One-shot guard to prevent duplicate notifications when enrollment threshold is crossed
  @Prop({ default: false })
  regenNotified: boolean;
}

export const QuizSchema = SchemaFactory.createForClass(Quiz);
