export enum NotificationType {
  COURSE_APPROVED = 'COURSE_APPROVED',
  COURSE_REJECTED = 'COURSE_REJECTED',
  COURSE_SUBMITTED_FOR_REVIEW = 'COURSE_SUBMITTED_FOR_REVIEW',
NEW_ENROLLMENT = 'NEW_ENROLLMENT',
NEW_REVIEW = 'NEW_REVIEW',
LOW_RATING = 'LOW_RATING',
 PURCHASE_COMPLETED = 'PURCHASE_COMPLETED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  COURSE_COMPLETED = 'COURSE_COMPLETED',
  CERTIFICATE_EARNED = 'CERTIFICATE_EARNED',
}
